# Generated by Django 4.2.7 on 2023-12-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dynamic_table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablecolumn',
            name='column_data_type',
            field=models.CharField(choices=[('char', 'Char'), ('int', 'Int'), ('float', 'Float'), ('bool', 'Bool'), ('textfield', 'TextField'), ('date', 'Date')], max_length=15),
        ),
    ]
